#ifndef __org_openoffice_adrianbelgun_i18n_simple_xsimplemenu_idl__
#define __org_openoffice_adrianbelgun_i18n_simple_xsimplemenu_idl__

#include <com/sun/star/document/XEventListener.idl>
#include <com/sun/star/ui/XContextMenuInterceptor.idl>
module org { module openoffice { module adrianbelgun { module i18n { module simple { 	

	interface XSimpleMenu {
		interface com::sun::star::document::XEventListener;
		interface com::sun::star::ui::XContextMenuInterceptor;

	};

 }; }; }; }; };
#endif
